name: Build geoip files
on:
  workflow_dispatch:
  schedule:
    # 每天凌晨 5:10（北京时间），等于 UTC 的 21:10 前一天
    - cron: "10 21 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Authenticate gh CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Checkout geoip repo
        run: gh repo clone Loyalsoldier/geoip

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geoip/go.mod
          cache-dependency-path: ./geoip/go.sum

      - name: Build geoip files
        run: |
          mv ./geoip-config.json geoip/config.json && cd geoip
          go build ./
          ./geoip convert -c ./config.json

      - name: Create release with current date tag
        run: |
          cd geoip/output
          mv geoip-only-cn-telegram-private.dat geoip-only-cn-telegram-private-$(date +%Y%m%d).dat
          gh release upload geoip --clobber geoip-only-cn-telegram-private-$(date +%Y%m%d).dat
          gh release upload geoip --clobber geoip-only-cn-telegram-private.dat
