name: r2s build openwrt

on:
  workflow_dispatch:
    inputs:
      openwrt_branch:
        description: 'OpenWrt Branch to build'     
        required: true
        default: '24.10.1'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git pull 
          git checkout v24.10.1
          echo "---- 1"
          ./scripts/feeds update -a
          echo "---- 2"
          ./scripts/feeds install -a
          echo "---- 3"
          cp ../r2s.config ./.config
          echo "---- 4"
          make -j$(nproc) defconfig download clean world
          echo "---- 5"
