name: r2s build openwrt

on:
  workflow_dispatch:
    inputs:
      openwrt_branch:
        description: 'OpenWrt Branch to build'     
        required: true
        default: '24.10.1'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git pull 
          git checkout openwrt-24.10.2
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../r2s.config ./.config
          make -j1 defconfig download clean world
